version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile

    image: my-ct3t-image
    container_name: my-ct3t-container

    ports:
      - "3000:3000"

    environment:
      - DATABASE_URL=postgres://ct3t-admin:ct3t-pass@db:5432/ct3t-db

    env_file:
      - .env

    depends_on:
      - db

  db:
    image: postgres:latest

    # used to create the database credentials
    environment:
      POSTGRES_USER: ct3t-admin
      POSTGRES_PASSWORD: ct3t-pass
      POSTGRES_DB: ct3t-db
      POSTGRES_PORT: 5432

    ports:
      - "5432:5432"
