variable "VERCEL_API_TOKEN" {}
variable "CLOUDFLARE_API_TOKEN" {}
variable "CLOUDFLARE_EMAIL" {}
variable "CLOUDFLARE_ZONE_ID" {}
variable "UPSTASH_EMAIL" {}
variable "UPSTASH_API_KEY" {}
variable "AWS_ACCESS_KEY" {}
variable "AWS_SECRET_KEY" {}
variable "PLANETSCALE_DB_URL_PRODUCTION" {}
variable "PLANETSCALE_DB_URL_PREVIEW" {}
variable "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY" {}
variable "CLERK_SECRET_KEY" {}