version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=postgres://ct3t-admin:ct3t-pass@db:5432/ct3t-db
        - UPSTASH_REDIS_REST_URL=http://localhost:8079
        - UPSTASH_REDIS_REST_TOKEN=ct3t-srh-token

    image: my-ct3t-image
    container_name: my-ct3t-container

    ports:
      - "3000:3000"

    env_file:
      - ../.env

    depends_on:
      - db

  db:
    image: postgres:latest

    environment:
      POSTGRES_USER: ct3t-admin
      POSTGRES_PASSWORD: ct3t-pass
      POSTGRES_DB: ct3t-db
      POSTGRES_PORT: 5432

    ports:
      - "5432:5432"

  cache:
    image: redis:latest

    ports:
      - "6379:6379"

  serverless-redis-http:
    image: hiett/serverless-redis-http:latest

    ports:
      - "8079:80"

    environment:
      SRH_MODE: env
      SRH_TOKEN: ct3t-srh-token
      SRH_CONNECTION_STRING: "redis://redis:6379"
