version: "3.8"

services:
  db:
    image: mysql:latest

    # used to create the database credentials
    environment:
      MYSQL_USER: ct3t-admin
      MYSQL_PASSWORD: ct3t-pass
      MYSQL_DATABASE: ct3t-db
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_PORT: 3306

    ports:
      - "3306:3306"

    volumes:
      - db_data:/var/lib/mysql
      # uncomment the next line to seed the database with a startup SQL script
      # also remove the persistent volume above to ensure successful seeding
      #- ./db-seed.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:latest

    ports:
      - "6379:6379"

  serverless-redis-http:
    image: hiett/serverless-redis-http:latest

    ports:
      - "8079:80"

    environment:
      SRH_MODE: env
      SRH_TOKEN: ct3t-srh-token
      SRH_CONNECTION_STRING: "redis://redis:6379"

    depends_on:
      - redis

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
    volumes:
      - s3_data:/tmp/localstack/data
    command: >
      sh -c '
        sleep 5;
        aws --endpoint-url=http://localhost:4566 s3 mb s3://ct3t-preview;
        echo "LocalStack ready!"'

volumes:
  db_data:
  s3_data:
