version: "3.8"

services:
  web:
    build:
      context: ../.
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=mysql://ct3t-admin:ct3t-pass@db:3306/ct3t-db
        - UPSTASH_REDIS_REST_URL=http://localhost:8079
        - UPSTASH_REDIS_REST_TOKEN=ct3t-srh-token

    image: my-ct3t-image
    container_name: my-ct3t-container

    ports:
      - "3000:3000"

    env_file:
      - ../.env

    depends_on:
      - db
      - cache
      - serverless-redis-http

  db:
    image: mysql:latest

    environment:
      MYSQL_USER: ct3t-admin
      MYSQL_PASSWORD: ct3t-pass
      MYSQL_DATABASE: ct3t-db
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_PORT: 3306

    ports:
      - "3306:3306"

  cache:
    image: redis:latest

    ports:
      - "6379:6379"

  serverless-redis-http:
    image: hiett/serverless-redis-http:latest

    ports:
      - "8079:80"

    environment:
      SRH_MODE: env
      SRH_TOKEN: ct3t-srh-token
      SRH_CONNECTION_STRING: "redis://redis:6379"
