version: "3.8"

services:
  db:
    image: postgres:latest

    # used to create the database credentials
    environment:
      POSTGRES_USER: ct3t-admin
      POSTGRES_PASSWORD: ct3t-pass
      POSTGRES_DB: ct3t-db
      POSTGRES_PORT: 5432

    ports:
      - "5432:5432"

    volumes:
      - db_data:/var/lib/postgresql/data
      #- ./postgres-seed.sql:/docker-entrypoint-initdb.d/init.sql - add startup SQL to seed the database

  redis:
    image: redis:latest

    ports:
      - "6379:6379"

  serverless-redis-http:
    image: hiett/serverless-redis-http:latest

    ports:
      - "8079:80"

    environment:
      SRH_MODE: env
      SRH_TOKEN: ct3t-srh-token
      SRH_CONNECTION_STRING: "redis://redis:6379"

volumes:
  db_data:
